---
# # # # #  User Setup  # # # # #

- name: "Random Password Facts"
  set_fact:
    random_password: "{{ lookup('password', '/dev/null length=20') | replace('\n', '') | replace(':', '') }}"
    use_random_pwd:  "{% if user.use_random_pwd | default(False) | bool and user.password is not defined %}True{% else %}False{% endif %}"

- name: "User Group Creation"
  group: name="{{ user.username }}" state=present
  when: user.state | default('present') == 'present'

- name: "Manage User"
  user:
    append:          "{{ user.append | default(omit) }}"
    comment:         "{{ user.comment | default(omit) }}"
    createhome:      "{{ user.createhome | default('yes') }}"
    expires:         "{{ user.expires | default(omit) }}"
    force:           "{{ user.force | default(omit) }}"
    group:           "{{ user.group | default(user.username) }}"
    groups:          "{{ user.groups | default([]) | join(',') }}"
    home:            "{{ user.home | default(omit) }}"
    login_class:     "{{ user.login_class | default(omit) }}"
    move_home:       "{{ user.move_home | default(omit) }}"
    name:            "{{ user.username }}"
    non_unique:      "{{ user.non_unique | default(omit) }}"
    password:        "{%- if use_random_pwd | bool %}{{ random_password }}{% else %}{{ user.password | default(omit) }}{% endif -%}"
    remove:          "{{ user.remove | default(omit) }}"
    seuser:          "{{ user.seuser | default(omit) }}"
    shell:           "{{ user.shell | default('/bin/bash') }}"
    skeleton:        "{{ user.skeleton | default(omit) }}"
    state:           "{{ user.state | default('present') }}"
    system:          "{{ user.system | default(omit) }}"
    uid:             "{{ user.uid | default(omit) }}"
    update_password: "{% if use_random_pwd | bool %}{{ user.update_password | default('on_create') }}{% else %}{{ user.update_password | default(omit) }}{% endif %}"
    ssh_key_comment: "{{ user.ssh_key_comment | default(omit) }}"
    ssh_key_bits:    "{{ user.ssh_key_bits | default(omit) }}"
    ssh_key_file:    "{{ user.ssh_key_file | default(omit) }}"
    ssh_key_passphrase: "{{ user.ssh_key_passphrase | default(omit) }}"
    generate_ssh_key: "{{ user.generate_ssh_key | default(omit) }}"
    ssh_key_type:    "{{ user.ssh_key_type | default(omit) }}"

- name: "User Group Deletion"
  group: name="{{ user.username }}" state=absent
  when: user.state | default('present') == 'absent'

- name: "Clear Secrets"
  set_fact:
    random_password: !!null
