---
# # # # #  Users Management  # # # # #

- name: "Require Correct Linux Distribution"
  assert:
    that: (ansible_distribution in ['CentOS', 'RedHat'] and ansible_distribution_version | version_compare('6.0.0', '>=')) or
          (ansible_distribution == 'Debian'             and ansible_distribution_version | version_compare('7.0.0', '>=')) or
          (ansible_distribution == 'Ubuntu'             and ansible_distribution_version | version_compare('14.0.0', '>='))
    msg:  "This Linux distrution '{{ ansible_distribution }} {{ ansible_distribution_version }}' is not supported by the role."
  tags: users

- name: "Group Creation"
  group:
    name:  "{{ item.name }}"
    gid:   "{{ item.gid | default( omit ) }}"
    state: present
  with_items: "{{ users_system_groups | default( [] ) }}"
  when: item.state | default( 'present' ) == 'present'
  tags: users

- name: "Set Up Local Users"
  include: local_user.yml
  with_items: "{{ users_system_users | default( [] ) }}"
  loop_control:
    loop_var: user
  when: user.type | default('local') == 'local'
  tags: users

- name: "Set Up Remote Users"
  include: remote_user.yml
  with_items: "{{ users_system_users | default( [] ) }}"
  loop_control:
    loop_var: user
  when: user.type | default('local') == 'remote'
  tags: users

- name: "Group Deletion"
  group:
    name:  "{{ item.name }}"
    gid:   "{{ item.gid | default( omit ) }}"
    state: absent
  with_items: "{{ users_system_groups | default( [] ) }}"
  when: item.state | default( 'present' ) == 'absent'
  tags: users
