---
# # # # #  User Setup  # # # # #

- name: "Create Home Directory : {{ user.username }}"
  command: "su - {{ user.username }} -c 'exit'"
  changed_when: false
  when: user.state | default('present') == 'present'
